"""
build_knowledge_base.py — Build Knowledge Base from Paramount+ Press Releases
Reads press releases from Snowflake, uses Claude API to synthesize insights,
saves output to knowledge_base/insights.md
"""

import os
import json
import logging
import anthropic
import snowflake.connector

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

SNOWFLAKE_ACCOUNT   = os.environ["SNOWFLAKE_ACCOUNT"]
SNOWFLAKE_USER      = os.environ["SNOWFLAKE_USER"]
SNOWFLAKE_PASSWORD  = os.environ["SNOWFLAKE_PASSWORD"]
SNOWFLAKE_DATABASE  = os.environ["SNOWFLAKE_DATABASE"]
SNOWFLAKE_WAREHOUSE = os.environ["SNOWFLAKE_WAREHOUSE"]


def fetch_press_releases() -> list[dict]:
    """Fetch press releases from Snowflake staging."""
    log.info("Connecting to Snowflake...")
    conn = snowflake.connector.connect(
        account=SNOWFLAKE_ACCOUNT,
        user=SNOWFLAKE_USER,
        password=SNOWFLAKE_PASSWORD,
        database=SNOWFLAKE_DATABASE,
        warouse=SNOWFLAKE_WAREHOUSE,
        schema="DBT_DEV_STAGING",
    )
    cur = conn.cursor()
    cur.execute("""
        SELECT title, published_date, url, summary, full_text
        FROM STG_PRESS_RELEASES
        WHERE full_text IS NOT NULL
          AND full_text != ''
        ORDER BY published_date DESC NULLS LAST
        LIMIT 30
    """)
    rows = cur.fetchall()
    cols = [desc[0] for desc in cur.description]
    cur.close()
    conn.close()
    releases = [dict(zip(cols, row)) for row in rows]
    log.info(f"Fetched {len(releases)} press releases")
    return releases


def synthesize_insights(releases: list[dict]) -> str:
    """Use Claude to synthesize key insights from press releases."""
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    # Build context from press releases
    context = ""
    for i, r in enumerate(releases[:20]):
        context += f"\n\n--- Press Release {i+1} ---\n"
        context += f"Title: {r['TITLE']}\n"
        context += f"Date: {r['PUBLISHED_DATE']}\n"
        context += f"URL: {r['URL']}\n"
        text = r['FULL_TEXT'] or r['SUMMARY'] or ""
        context += f"Content: {text[:1500]}\n"

    prompt = f"""You are a marketing analytics expert analyzing Paramount+ content strategy.

Below are {len(releases[:20])} recent Paramount+ press releases. Analyze them and produce a structured knowledge base with the following sections:

1. **Content Strategy Themes** — What types of content is Paramount+ prioritizing? (new shows, renewals, casting, sports, etc.)

2. **Key Titles & Franchises** — Which shows, movies, or franchises are getting the most press attention?

3. **Marketing Angles** — What messaging themes appear repeatedly? (exclusivity, star power, seasons, premieres)

4. **Audience Targeting Insights** — What audience segments does the content seem aimed at?

5. **Competitive Positioning** — How does Paramount+ position itself based on this content?

6. **Paid Social Implications** — Given this content slate, what campaigns shouldrioritize? Which titles would make the best retargeting vs prospecting campaigns?

7. **Key Dates & Opportunities** — Upcoming premieres or events that represent marketing opportunities.

Be specific, cite actual titles from the press releases, and make the insights actionable for a paid social marketing analyst.

PRESS RELEASES:
{context}
"""

    log.info("Calling Claude API to synthesize insights...")
    message = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=4000,
        messages=[{"role": "user", "content": prompt}]
    )

    return message.content[0].text


def save_knowledge_base(insights: str, releases: list[dict]) -> None:
    """Save the knowledge base to a markdown file."""
    os.makedirs("knowledge_base", exist_ok=True)

    # Build index of press releases
    index = "\n".join([
        f"- [{r['TITLE'][:80]}]({r['URL']}) — {r['PUBLISHED_DATE']}"
        for r in releases
    ])

    content = f"""# Paramount+ Marketing Knowledge Base

*Generated by Claude  {len(releases)} press releases scraped from Paramount+ Press Express*

---

## AI-Synthesized Insights

{insights}

---

## Press Release Index

{index}
"""

    with open("knowledge_base/insights.md", "w") as f:
        f.write(content)

    log.info("Knowledge base saved to knowledge_base/insights.md")


def main():
    releases = fetch_press_releases()
    if not releases:
        log.warning("No press releases found. Run scrape_load.py first.")
        return

    insights = synthesize_insights(releases)
    save_knowledge_base(insights, releases)
    log.info("Knowledge base complete ✓")


if __name__ == "__main__":
    main()
